name: apolloshop
description: "Apollo Shop - Android mobile app for Apollo ecommerce platform. Designed for customers to browse products, manage carts, and make purchases easily."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & Utilities
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  connectivity_plus: ^5.0.1
  flutter_secure_storage: ^5.0.2

  # UI & Animation
  lottie: ^2.7.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  flutter_native_splash: ^2.3.2

  # Media & Assets
  image_picker: ^1.0.4
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0

  # Icons & Fonts
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management & Storage
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/banners/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
